[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NEXT_PUBLIC_CHANNEL_ID = "UCvdF9H49FJVtZX3MZ480Fcg"
  NEXT_PUBLIC_YOUTUBE_API_KEY = "AIzaSyAyq6RhOQqJJoLcgvQsZMy5eaPkLOWuLw0"

# Disable secrets scanning for specific paths
[secrets]
  SECRETS_SCAN_OMIT_PATHS = ".netlify/.next/cache/webpack/*, .netlify/.next/server/*, .netlify/.next/static/*, .netlify/functions-internal/*, .next/*"
